#!/bin/sh

if (grep "ColorScheme=ArcDark" ~/.config/kdeglobals);

then konsoleprofile colors="Arc";

sed -i 's:.*DefaultProfile.*:DefaultProfile=Day.profile:' ~/.config/konsolerc;

lookandfeeltool --apply com.github.sayan.day;

kquitapp5 plasmashell && kstart5 plasmashell;

sed -i 's:.*Net/ThemeName.*:Net/ThemeName "Arc":; s:.*Net/IconThemeName.*:Net/IconThemeName "Papirus-Light":' ~/.config/xsettingsd/xsettingsd.conf;

xsettingsd &

fi
