#!/bin/sh

source themes

if ! grep -Eq "LookAndFeelPackage=$global_light$" /home/$(whoami)/.config/kdeglobals
then lookandfeeltool --apply $global_light
fi


if ! grep -Eq "ColorScheme=$konsole_light$" /home/$(whoami)/.local/share/konsole/Adaptive.profile
then sed -i "s:.*ColorScheme.*:ColorScheme=$konsole_light:" /home/$(whoami)/.local/share/konsole/Adaptive.profile
konsoleprofile colors=$konsole_light
qdbus org.kde.yakuake /yakuake/sessions org.kde.yakuake.runCommand 'konsoleprofile colors=$konsole_light'
fi


DP=`loginctl show-session $(loginctl | grep $(whoami) | awk '{print $1}') -p Type`
if [[ $DP =~ "wayland" ]]
then gtk_current=`gsettings get org.gnome.desktop.interface gtk-theme`
gtk_current=${gtk_current//\'}
if [[ "$gtk_current" != "$gtk_light" ]]
then gsettings set org.gnome.desktop.interface gtk-theme $gtk_light
fi
else if ! grep -Eq "Net\/ThemeName \"$gtk_light\"$" /home/$(whoami)/.config/xsettingsd/xsettingsd.conf
then sed -i "s:.*Net/ThemeName.*:Net/ThemeName \"$gtk_light\":" /home/$(whoami)/.config/xsettingsd/xsettingsd.conf && xsettingsd &
fi
fi
