#!/bin/sh

mkdir -p ~/.local/share/plasma/look-and-feel;

cp -r ./com.github.sayan.day ~/.local/share/plasma/look-and-feel/;

cp -r ./com.github.sayan.night ~/.local/share/plasma/look-and-feel/;

chmod a+x ./day;

chmod a+x ./night;

mkdir -p ~/.local/bin;

cp ./day ~/.local/bin/;

cp ./night ~/.local/bin/;

cp ./Day.profile ~/.local/share/konsole/;

cp ./Night.profile ~/.local/share/konsole/;
