#!/bin/sh

#KDE Plasma Global themes [/usr/share/plasma/look-and-feel/] or [~/.local/share/plasma/look-and-feel/]
global_light=org.kde.breeze.desktop;
global_dark=org.kde.breezedark.desktop;


#GTK themes [/usr/share/themes/] or [~/.themes/]
gtk_light=Adwaita;
gtk_dark=Adwaita-dark;


#Konsole ColorSchemes [/usr/share/konsole/*.colorscheme] or [~/.local/share/konsole/*.colorscheme]
konsole_light=SolarizedLight;
konsole_dark=Solarized;
